# Generated by Django 5.2.5 on 2025-09-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_document_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
